/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

//import { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Pokeball(props) {
  const { nodes, materials } = useGLTF("/models/quikPokeball.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere_1.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere_2.geometry}
        material={materials["Material.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere_3.geometry}
        material={materials["Material.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere_4.geometry}
        material={materials["Material.004"]}
      />
    </group>
  );
}

useGLTF.preload("/models/quikPokeball.gltf");

