/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

//import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export function Pokeball(props) {
    const { nodes, materials } = useGLTF("/models/quikPokeball.gltf");
    return (

        <RigidBody colliders="hull" position={[3 - Math.random() * 6, 3 - Math.random() * 6, 3 - Math.random() * 6]} >
            <group dispose={null}

                onClick={(e) => console.log('clicked ' + props.id)}
                onContextMenu={(e) => console.log('context menu')}
                onDoubleClick={(e) => console.log('double click')}
                onWheel={(e) => console.log('wheel spins')}
            >

                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere_1.geometry}
                    material={materials["Material.001"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere_2.geometry}
                    material={materials["Material.002"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere_3.geometry}
                    material={materials["Material.003"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Icosphere_4.geometry}
                    material={materials["Material.004"]}
                />
            </group>
        </RigidBody>
    );
}

useGLTF.preload("/models/quikPokeball.gltf");

